### ISSUE TITLE
Will there be a v14 compatible version of "snapshots" ?

### ISSUE THREAD

**Issue by ediazcomellas** [icewind1991/files_snapshots#17]
Hi,

This plugin is the only one I miss in v14. I think it is great to integrate snapshots between ZFS and NC. My users find it extremely useful.

Are you planning to make it compatible to v14?

Thanks

**Comment by BMTTeam** [comment]
Same here. The only one plugin holding back the update to v14.
I hope that there will be new version soon.

Cheers,
-Tiho

**Comment by icewind1991** [comment]
Published a v14 compatible release
