### ISSUE TITLE
Compatibility with NC 15

### ISSUE THREAD

**Issue by SaltyCybernaut** [icewind1991/files_snapshots#19]
This is an excellent app for Nextcloud. Are there plans to make it compatible with NC 15?

**Comment by rev138** [comment]
I tried merely bumping the max version parameter in info.xml, and nextcloud installs it without complaint, but when I try to access the 'Versions' tab on a file it's empty and the browser console throws a CSP error :(

**Comment by SaltyCybernaut** [comment]
@rev138 you issue is most likely due to issue #12

**Comment by icewind1991** [comment]
It took a while, but 0.2.0 is compatible with NC15 and 16

**Comment by SaltyCybernaut** [comment]
@icewind1991 Excellent work! Your hard work is appreciated!
