### ISSUE TITLE
Does 'files_snapshots' work with NC18?

### ISSUE THREAD

**Issue by ghost** [icewind1991/files_snapshots#24]
Does snapshots work with NC18? Is it enough to choose "Enable untested app"?

**Comment by DragonQ** [comment]
I'd also like to know this!

**Comment by totaltmega** [comment]
I enabled it and I got it to work with btrfs snapshots.
However, I could not "revert" the file but I could download old versions of the file.

**Comment by marc-henri** [comment]
Hi,
I've got the same problemn than @totaltmega 
As described in this picture, snapshot are done bye the operatinge system, they are store in /srv/backup/snapshots folder, and their names are detect but not the date.
My nextcloud version is 18.0.x and file_snapshots's version is 0.3.0

![configuration-snapshot](https://user-images.githubusercontent.com/28484154/79687052-db7cd600-8244-11ea-9e27-26f916f4c151.png)

**Comment by marc-henri** [comment]
Sorry, that's not really the same problemn than @totaltmega because i can't download any other version other than the original file.
Maybe i don't know how to use rightly this application.

**Comment by DragonQ** [comment]
@marc-henri your problem is likely just that your "date format" is incorrect. I had a similar problem; try changing `*-*_Y-m-d_His` to `*Y-m-d_His`.

I've tried enabling the untested app and have the same results as @totaltmega. I sees my snapshots and lets me download old versions of files, but I cannot restore old versions of files.

**Comment by totaltmega** [comment]
@marc-henri  yes you have the date incorret

Here is my setup for my date for reference:
![bild](https://user-images.githubusercontent.com/6403600/80357886-e86c7b80-887b-11ea-9c49-64805880177d.png)

**Comment by icewind1991** [comment]
A new release for nc 20/21 has been released
