### ISSUE TITLE
Scrolling errors from SnapshotManager.php after fresh install.

### ISSUE THREAD

**Issue by MrGreaterThan** [icewind1991/files_snapshots#34]
I'm not a linux expert yet, so hopefully this isn't caused by some simple thing that I've messed up.

I have a NextCloud container installed onto an UnRaid server. I just got the server running and I was looking to all the cool addons and found yours. After installing it, it filled my error log with the error below. The errors stopped as soon as I disabled the addon.

Error: Undefined offset: 1 at /config/www/nextcloud/apps/files_snapshots/lib/SnapshotManager.php#49

> /config/www/nextcloud/apps/files_snapshots/lib/SnapshotManager.php - line 49:
> 
> OC\Log\ErrorHandler::onError()
> 
> /config/www/nextcloud/apps/files_snapshots/lib/AppInfo/Application.php - line 38:
> 
> OCA\Files_Snapshots\SnapshotManager->__construct()
> 
> /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 155:
> 
> OCA\Files_Snapshots\AppInfo\Application->OCA\Files_Snapshots\AppInfo\{closure}("*** sensiti ... *")
> 
> /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php - line 118:
> 
> OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")
> 
> /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 122:
> 
> Pimple\Container->offsetGet()
> 
> /config/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 453:
> 
> OC\AppFramework\Utility\SimpleContainer->query()
> 
> /config/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 431:
> 
> OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
> 
> /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 87:
> 
> OC\AppFramework\DependencyInjection\DIContainer->query()
> 
> <<closure>>
> 
> OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")
> 
> /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 101:
> 
> array_map()
> 
> /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 109:
> 
> OC\AppFramework\Utility\SimpleContainer->buildClass()
> 
> /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 126:
> 
> OC\AppFramework\Utility\SimpleContainer->resolve()
> 
> /config/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 459:
> 
> OC\AppFramework\Utility\SimpleContainer->query()
> 
> /config/www/nextcloud/lib/private/ServerContainer.php - line 146:
> 
> OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
> 
> /config/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 434:
> 
> OC\ServerContainer->query()
> 
> /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 56:
> 
> OC\AppFramework\DependencyInjection\DIContainer->query()
> 
> /config/www/nextcloud/apps/files_versions/lib/AppInfo/Application.php - line 123:
> 
> OC\AppFramework\Utility\SimpleContainer->get()
> 
> /config/www/nextcloud/apps/files_versions/lib/AppInfo/Application.php - line 106:
> 
> OCA\Files_Versions\AppInfo\Application->loadBackend()
> 
> /config/www/nextcloud/lib/private/AppFramework/Bootstrap/FunctionInjector.php - line 68:
> 
> OCA\Files_Versions\AppInfo\Application->registerVersionBackends()
> 
> /config/www/nextcloud/lib/private/AppFramework/Bootstrap/BootContext.php - line 52:
> 
> OC\AppFramework\Bootstrap\FunctionInjector->injectFn()
> 
> /config/www/nextcloud/apps/files_versions/lib/AppInfo/Application.php - line 91:
> 
> OC\AppFramework\Bootstrap\BootContext->injectFn()
> 
> /config/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php - line 176:
> 
> OCA\Files_Versions\AppInfo\Application->boot()
> 
> /config/www/nextcloud/lib/private/legacy/OC_App.php - line 197:
> 
> OC\AppFramework\Bootstrap\Coordinator->bootApp()
> 
> /config/www/nextcloud/lib/private/legacy/OC_App.php - line 137:
> 
> OC_App::loadApp()
> 
> /config/www/nextcloud/apps/dav/lib/AppInfo/Application.php - line 124:
> 
> OC_App::loadApps()
> 
> /config/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php - line 176:
> 
> OCA\DAV\AppInfo\Application->boot()
> 
> /config/www/nextcloud/lib/private/legacy/OC_App.php - line 197:
> 
> OC\AppFramework\Bootstrap\Coordinator->bootApp()
> 
> /config/www/nextcloud/lib/private/legacy/OC_App.php - line 137:
> 
> OC_App::loadApp()
> 
> /config/www/nextcloud/lib/base.php - line 979:
> 
> OC_App::loadApps()
> 
> /config/www/nextcloud/index.php - line 37:
> 
> OC::handleRequest()

**Comment by icewind1991** [comment]
Fixed with 1.0.1
