### ISSUE TITLE
Limit apps access to a group

### ISSUE THREAD

**Issue by fossxplorer** [icewind1991/files_snapshots#5]
Is it possible with this app?

Thanks a lot for this awesome app @icewind1991. Looking forward to be testing with ZFS!

**Comment by zeigerpuppy** [comment]
I agree, limiting to a group would be great for testing purposes.
I'm also going to try with ZFS, looks like a great solution.

**Comment by icewind1991** [comment]
This should already be possible as with most other apps, there should be a checkbox in the installed apps list
