### ISSUE TITLE
basic usage

### ISSUE THREAD

**Issue by nimrodl** [icewind1991/files_snapshots#6]
I'm not sure what I'm doing wrong here, but I've put in the path to the snapshots and the list of snapshots gets detected, but no dates and I don't see any file versions in the file viewer.  

I'm using nextcloud version 12 on FreeBSD 11.1 from the FreeBSD package repository on zfs.  I have a zfs dataset zroot/data mounted at /usr/local/www/nextcloud/data.

my snapshot format is defined as: /usr/local/www/nextcloud/data/.zfs/snapshot/%snapshot%/
and the date format is: Y-m-d-H-i
an actual snapshot name is: hourly-2017-08-04-20

**Comment by tacruc** [comment]
Propably your date format is wrong. You should play around with it, until you see the dates in the snapshot list. 
Try:
*Y-m-d-H
and
Y-m-d-H

**Comment by tacruc** [comment]
Mode about the meaning can bei foundation there:

http://php.net/manual/de/datetime.createfromformat.php

**Comment by nimrodl** [comment]
The leading * did the trick.  

Now the next bit, the snapshot script I'm using creates different formats.

daily-2017-08-05
hourly-2017-08-04-20

Can both be accommodated at the same time?
